### ISSUE TITLE
Mixin crash during startup in production environment - cannot reference a `@Local` parameter by name

### ISSUE THREAD

**Issue by unilock** [JSJBDEV/Reforested#1]
https://github.com/JSJBDEV/Reforested/blob/7d49fd1e94423369108ffb9bc9fa6eccd289fa6e/src/main/java/ace/actually/reforested/mixin/BeehiveEntityMixin.java#L97

> `@Local(name="i") LocalIntRef localRef`

A local variable cannot be referenced by `name` in the context of obfuscated code, such as Minecraft's, since the game has no knowledge of such local variable names during runtime. You'll have to use `ordinal` and/or `index`.

Crash log: https://gist.github.com/unilock/63be6dd1f5065cb793013338c6322cf6

**Comment by JSJBDEV** [comment]
oh neat, I really should have tested in prod huh. will attempt to fix now

**Comment by JSJBDEV** [comment]
ye fixed in like 10 seconds, sorry about the wait, time be timing
